# Generated by Django 5.0.4 on 2024-04-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(upload_to='NavigationImage')),
                ('route', models.TextField()),
            ],
        ),
    ]
